source ~/.dotfiles/zsh/aliases.zsh
source ~/.dotfiles/zsh/settings.zsh
source ~/.dotfiles/zsh/prompt.zsh
source ~/.dotfiles/zsh/git.zsh
source ~/.dotfiles/zsh/history.zsh
source ~/.dotfiles/zsh/secrets.zsh

export FZF="$HOME/.fzf.zsh"
[ -f $FZF ] && source $FZF

export ASDF=$(brew --prefix asdf)
[ -d $ASDF ] && export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"

